sites/sandbox/apps/designer/urls.py
from django.conf.urls import url

from designer import views

urlpatterns = [
    url(r'^$', views.Designer_list.as_view(), name='list'),
    url(r'^(?P<designer_slug>[\w-]*)_(?P<pk>\d+)/$', views.Designer_profile.as_view(), name='profile'),
    url(r'^(?P<designer_slug>[\w-]*)_(?P<lookbook_slug>[\w-]*)_(?P<pk>\d+)/$', views.Lookbook_list.as_view(),
        name='lookbook'),
]



sites/sandbox/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf.urls.static import static

from oscar.app import shop
from oscar.views import handler500, handler404, handler403  # noqa

from apps.sitemaps import base_sitemaps


admin.autodiscover()

urlpatterns = [
    # Include admin as convenience. It's unsupported and you should
    # use the dashboard
    url(r'^admin/', include(admin.site.urls)),
    # i18n URLS need to live outside of i18n_patterns scope of the shop
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # include a basic sitemap
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.index', {
        'sitemaps': base_sitemaps}),
    
    url(r'^sitemap-(?P<section>.+)\.xml$',
        'django.contrib.sitemaps.views.sitemap', {'sitemaps': base_sitemaps}),
    # @ajit: URLS added for allauth access
    url(r'^accnt/', include('allauth.urls')),
    url(r'^relationships/', include('relationships.urls')),
]

# Prefix Oscar URLs with language codes
urlpatterns += i18n_patterns('',
    # Custom functionality to allow dashboard users to be created
    url(r'gateway/', include('apps.gateway.urls')),
    url(r'request/', include('apps.request.urls', namespace='request', app_name='request')),
    # @vivek: added new url for designer access on first page
    url(r'designer/', include('apps.designer.urls', namespace='designer', app_name='designer')),
    # @ajit: Payment gateway URL
    url(r'payzippy/', include('apps.payzippy.urls', namespace='payzippy', app_name='payzippy')),
    # @ajit: Relationships URL
    # url(r'relationships/', include('relationships.urls', namespace='relationships', app_name='relationships')),
    # Oscar's normal URLs
    url(r'', include(shop.urls)),

)

if settings.DEBUG:
    import debug_toolbar

    # Server statics and uploaded media
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    # Allow error pages to be tested
    urlpatterns += [
        url(r'^403$', handler403),
        url(r'^404$', handler404),
        url(r'^500$', handler500),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

sites/sandbox/apps/designer/models.py
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.db import models
from oscar.core.compat import AUTH_USER_MODEL

# from oscar.apps.catalogue.models import Product


class Designer(models.Model):
    designer = models.ForeignKey(AUTH_USER_MODEL, limit_choices_to={'is_designer': True},
                                 verbose_name=_("Designer Email"), null=True, blank=True, unique=True)

    slug = models.SlugField(_('Slug'), max_length=255, editable=False)

    def save(self, *args, **kwargs):
        self.slug = self.designer.username
        super(Designer, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('designer:profile', kwargs={'designer_slug': self.slug, 'pk': self.designer.id})

    def __unicode__(self):
        return unicode(self.designer.get_full_name())
        

class DesPostCategory(models.Model):
    designer = models.ForeignKey(Designer, related_name='desig')
    name = models.CharField(max_length=30, default='default')
    date_created = models.DateTimeField(_('Date created'), auto_now_add=True, null=True)

    class Meta:
        unique_together = ("designer", "name")
        verbose_name = _("Post Category")
        verbose_name_plural = _("Post Categories")

    def __unicode__(self):
        return unicode(self.name)


class DesignerPost(models.Model):
    

    category = models.ForeignKey(DesPostCategory, related_name="categ", null=True)
    name = models.CharField(_('Name'), max_length=30, unique=True)
    designer = models.ForeignKey('Designer', related_name="des", null=True)
    post_status = models.CharField(_('Post Status'), max_length=30, blank=True)
    description = models.TextField()
    date_created = models.DateTimeField(_('Date created'), auto_now_add=True, null=True)
    last_edited = models.DateTimeField(_('Last edited'), auto_now_add=True, null=True)
    
    class Meta:
        verbose_name = _("Designer Post")
        verbose_name_plural = _("Designer Posts")

    def __unicode__(self):
        post_description = '%s: %s' % (self.designer, self.name)
        return unicode(post_description)

class DesPostImage(models.Model):
    post = models.ForeignKey(DesignerPost, related_name='postimage')
    image = models.ImageField(upload_to='Designer/Post/Images', blank=True, null=True)


class DesVideoUrl(models.Model):
    post = models.ForeignKey(DesignerPost, related_name='postvideo')
    video_url = models.URLField(blank=True)
	

sites/sandbox/apps/dashboard/designer/views.py
import six

from django.core.exceptions import ObjectDoesNotExist
from django.views import generic
from django.db.models import Q
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.template.loader import render_to_string

from oscar.core.loading import get_classes, get_model
from oscar.views import sort_queryset
from oscar.views.generic import ObjectLookupView

(ProductForm,
 ProductClassSelectForm,
 ProductSearchForm,
 ProductClassForm,
 CategoryForm,
 StockRecordFormSet,
 StockAlertSearchForm,
 ProductCategoryFormSet,
 ProductImageFormSet,
 ProductRecommendationFormSet) \
    = get_classes('dashboard.catalogue.forms',
                  ('ProductForm',
                   'ProductClassSelectForm',
                   'ProductSearchForm',
                   'ProductClassForm',
                   'CategoryForm',
                   'StockRecordFormSet',
                   'StockAlertSearchForm',
                   'ProductCategoryFormSet',
                   'ProductImageFormSet',
                   'ProductRecommendationFormSet'))
Product = get_model('catalogue', 'Product')

DesLookbook = get_model('catalogue','DesLookbook')

Category = get_model('catalogue', 'Category')
ProductImage = get_model('catalogue', 'ProductImage')
ProductCategory = get_model('catalogue', 'ProductCategory')
ProductClass = get_model('catalogue', 'ProductClass')
StockRecord = get_model('partner', 'StockRecord')
StockAlert = get_model('partner', 'StockAlert')
Partner = get_model('partner', 'Partner')



def filter_lookbooks(queryset, user):
    """
    Restrict the queryset to products the given user has access to.
    A staff user is allowed to access all Products.
    A non-staff user is only allowed access to a product if they are in at
    least one stock record's partner user list.
    """
    if user.is_staff:
        return queryset

    return queryset.filter(stockrecords__partner__users__pk=user.pk).distinct()



class LookbookListView(generic.ListView):
    
    template_name = 'dashboard/designer/lookbook_list.html'
    model = DesLookbook
    context_object_name = 'lookbooks'

    def get_context_data(self, **kwargs):
        context = super(LookbookListView, self).get_context_data(**kwargs)
        return context

    def filter_queryset(self, queryset):
        """
        Apply any filters to restrict the products that appear on the list
        """
        return filter_lookbooks(queryset, self.request.user)

    # def get_queryset(self):
    #     """
    #     Build the queryset for this list
    #     """
    #     queryset = DesLookbook.objects.base_queryset()
    #     queryset = self.filter_queryset(queryset)
    #     queryset = self.apply_search(queryset)
    #     queryset = self.apply_ordering(queryset)

    #     return queryset
# ---------------------------------------------

sites/sandbox/apps/designer/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response
from request.forms import *
from oscar.core.compat import get_user_model
from django.shortcuts import get_object_or_404
# from . import signals
from django.views.generic import ListView, DetailView
from designer.models import Designer, DesignerPost
from catalogue.models import DesLookbook


User = get_user_model()


#The object list will always have the name 'object_list', if you want to change this 
#behaviour, you must pass in context_object_name as a keyword argument to the as_view() 
#in the url alongside model / paginate_by etc. 
#Or you must define it in your class if you are using the class to write views.

#What if my queryset / model returns no object. This case will raise a 404 error, 
#unless you pass in an allow_empty = True keyword into the as_view() 
#or define it in your class. 

class Designer_list(ListView):
    model = Designer
    #queryset = Designer.objects.filter(myfield="foo")
    # context_object_name = ""
    template_name = 'designer/list.html'
    #paginate_by = settings.OSCAR_PRODUCTS_PER_PAGE
    #enforce_paths = True


    def get_context_data(self, **kwargs):
        context = super(Designer_list, self).get_context_data(**kwargs)
        context['designers'] = Designer.objects.all()
        context['lookbooks'] = DesLookbook.objects.all()
        return context


class Designer_profile(DetailView):
    model = Designer
    template_name = 'designer/profile.html'
    def get_object(self):
        if 'pk' in self.kwargs:
            self.designer = get_object_or_404(Designer, pk=self.kwargs['pk'])

    #     elif 'category_slug' in self.kwargs:
    #         # For SEO reasons, we allow chopping off bits of the URL. If that
    #         # happened, no primary key will be available.
    #         self.designer = get_object_or_404(
    #             Designer, slug=self.kwargs['designer_slug'])
    #     else:
    #         # If neither slug nor primary key are given, we show all products
    #         self.designer = None  

    def get_context_data(self, **kwargs):
        designer = User.objects.get(id=self.kwargs['pk'])
        
        print "GET CONTEXT DATA---->"
        print designer.pk
        print designer.username

        posts = DesignerPost.objects.get(designer=self.kwargs['pk'])
        context = super(Designer_profile, self).get_context_data(**kwargs)
        context['designer'] = designer
        context['posts'] = posts
        return context


class Lookbook_list(ListView):
    model = Designer
    #queryset = Designer.objects.filter(myfield="foo")
    # context_object_name = ""
    template_name = 'designer/lookbook.html'
    #paginate_by = settings.OSCAR_PRODUCTS_PER_PAGE
    #enforce_paths = True


    def get_context_data(self, **kwargs):
        print self.kwargs
        p = DesLookbook.objects.all()
        context = super(Designer_list, self).get_context_data(**kwargs)

        context['designers'] = Designer.objects.all()
        # context['lookbooks'] = DesLookbook.objects.order_by('-designer')
        context['lookbooks'] = DesLookbook.objects.all()
        return context


        # def get_categories(self):
        #     """
        #     Return a list of the current category and it's ancestors
        #     """
        #     return list(self.category.get_descendants()) + [self.category]

        # def get_summary(self):
        #     """
        #     Summary to be shown in template
        #     """
        #     return self.category.name if self.category else _('All products')

        # def get_context_data(self, **kwargs):
        #     context = super(ProductCategoryView, self).get_context_data(**kwargs)
        #     context['category'] = self.category
        #     context['summary'] = self.get_summary()
        #     return context

        # def get_queryset(self):
        #     qs = Product.browsable.base_queryset()
        #     if self.category is not None:
        #         categories = self.get_categories()
        #         qs = qs.filter(categories__in=categories).distinct()
        #     return qs


### We are using a simple view to direct the success url returned by
def Request_Success(request):
    context = RequestContext(request)
    return render_to_response('request/success.html', {}, context)

sites/sandbox/templates/designer/list.html
{% extends "layout_2_col.html" %}

{% load basket_tags %}
{% load promotion_tags %}
{% load category_tags %}
{% load product_tags %}
{% load i18n %}
{% load relationship_tags %}

{% block title %}
{{ summary }} | {{ block.super }}
{% endblock %}

{% block description %}
{{ category.description|default:""|striptags }}
{% endblock %}

{% block headertext %}{{ summary }}{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li>
    <a href="{{ homepage_url }}">{% trans "Home" %}</a>
    <span class="divider">/</span>
  </li>
  <li class="active">{% trans "Designers" %}</li>
</ul>
{% endblock breadcrumbs %}


{% block column_left %}
{% if lookbooks %}
<div class="lookbooks" style="padding: 8px 0;">
  <ul class="nav nav-list">
    <li class="nav-header">{% trans "Browse LookBooks" %}</li>
    <li class="dropdown-submenu">
      {% for des in designers %}
      <li><strong>{{ des.name }}</strong></li>
      {% for l in des.lookbooks.all %}
      <li><a tabindex="-1" href="{{ l.get_absolute_url }}">{{ l.name }}</a></li>
      {% endfor %}
      <li class="divider"></li>
      {% endfor %} 

    </ul>
  </div>
  {% endif %}
  {% endblock %}

  {% block content %}
  {% if designers %}
  {% for designer in designers %}

  <div class="row">
    </br></br>
    <div class="span2">
      <img src="{{MEDIA_URL}}{{ designer.designer.profile_pic }}"  alt="" class="img-rounded">
    </div>
    <div class="span4">
      <blockquote>
        <p><a href="{{ designer.get_absolute_url }}">{{ designer.designer.get_full_name }}</a></p>
        <small><cite title="Source Title">Gotham, United Kingdom  <i class="icon-map-marker"></i></cite></small>
      </blockquote>
      <p>
        <i class="icon-envelope"></i> {{ designer.designer.email }}<br>
        <i class="icon-globe"></i> www.bootsnipp.com <br>
        <i class="icon-gift"></i> January 30, 1974

      {% if request.user != designer.designer %}

        {# decide whether or not the current user is following this user #}

          {% if_relationship request.user designer.designer "following" %}

          {# they are following them, so show a "remove" url #}
          <a href="{{ designer.designer|remove_relationship_url:"following" }}">Unfollow</a>

          {% else %}

          {# they are not following them, so show a link to start following #}


          {% endif_relationship %}

        {% else %}
        <p>This is you!</p>
      {% endif %}
      </p>
    </div>
  </div>
 
{% endfor %}
{% else %}
<p class="nonefound">{% trans "No designer found." %}</p>
{% endif %}
{% endblock content %}


sites/sandbox/templates/designer/lookbook_list.html
{% extends 'dashboard/layout.html' %}
{% load i18n %}
{% load thumbnail %}
{% load staticfiles %}
{% load sorting_tags %}

{% block body_class %}{{ block.super }} catalogue{% endblock %}

{% block title %}
{% trans "Lookbooks" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
    <li>
        <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        <span class="divider">/</span>
    </li>
    <li class="active">{% trans "Lookbooks" %}</li>
</ul>
{% endblock %}

{% block header %}
<div class="page-header action">
    <h1>{% trans "Lookbooks" %}</h1>
</div>

<ul>
    {% for lookbook in lookbooks %}
    <li>{{ lookbook.name }} - {{ lookbook.designer }} - {{ lookbook.description }} - 
        {% for product in lookbook.products.all %}
        <li>
           {% with image=product.primary_image %}
           {% thumbnail image.original "70x70" upscale=False as thumb %}
           <a href="{{ image.original.url }}" rel="lightbox_{{ product.upc|default:"-" }}" class="sub-image">
            <img src="{{ thumb.url }}" alt="{{ product.get_title }}" data-description="{% if image.caption %}{{ image.caption }}{% endif %}">
        </a>
        {% endthumbnail %}
        {% endwith %}
    </li>
    {% endfor %}
</li>
{% empty %}
<li>No Lookbooks yet.</li>
{% endfor %}
</ul>

{% endblock header %}

sites/sandbox/templates/designer/profile.html
{% extends "layout_2_col.html" %}

{% load thumbnail %}
{% load i18n %}
{% load display_tags %}
{% load staticfiles %}

{% block title %}
{{ summary }} | {{ block.super }}
{% endblock %}

{% block description %}
{{ category.description|default:""|striptags }}
{% endblock %}

{% block headertext %}{{ summary }}{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
	<li>
		<a href="{{ homepage_url }}"><strong>{% trans "Home " %}</strong>/</a>
		<!--  <span class="divider">/</span> -->
	</li>
	<li>
		<a href="{% url 'designer:list' %}">{% trans "Designers " %}/</a>
	</li>
	<li class="active">{{designer}}</li>
</ul>
{% endblock breadcrumbs %}

{% block column_left %}
<b>This is block column left.</b>
{% endblock %}

{% block content %}

<img src="{{MEDIA_URL}}{{ designer.designer.profile_pic }}" alt="{{ designer.designer }}" height="15%" width="20%">
</br></br>

<table class="table table-striped table-bordered">
	<tbody>
		<tr>
			<th>{% trans 'Name' %}</th>
			<td>{{ designer.designer.get_full_name|default:'-' }}</td>
		</tr>
		<tr>
			<th>{% trans 'Email address' %}</th>
			<td>{{ designer.designer.email }}</td>
		</tr>
		{% block profile_fields %}
		{% for field in profile_fields %}
		<tr>
			<th>{{ field.name }}</th>
			<td>{{ field.value|default:"-" }}</td>
		</tr>
		{% endfor %}
		{% endblock %}
		<tr>
			<th>{% trans 'Date registered' %}</th>
			<td>{{ designer.date_joined }}</td>
		</tr>
		<tr>
			<th>{% trans 'Lookbooks' %}</th>
			<td>{% for lookbook in designer.lookbooks.all %}
				<p><strong>{{lookbook.name}}</strong></p>

				{% for product in lookbook.products.all %}
				{% block product_image %}
				<div class="image_container">
					{% with image=product.primary_image %}
					{% thumbnail image.original "x155" upscale=False as thumb %}
					<a href="{{ product.get_absolute_url }}"><img src="{{ thumb.url }}" alt="{{ product.get_title }}" class="thumbnail"></a>
					{% endthumbnail %}
					{% endwith %}
				</div>
				{% endblock %}
				{% endfor %}
				<li class="divider"></li>
				{% endfor %}</td>
			</tr>
			<tr>
				<th>{% trans 'Styles' %}</th>
				<td>{% for post in designer.DesignerPost.all %}
					{% block post %}
					<strong>{{ post.name }}</strong>
					{% endblock post %}
					{% empty %}
					<p>No Styles uploaded yet</p>
					{% endfor %}</td>
				</tr>
			</tbody>
		</table>
		{% endblock %}
